config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "works#index"

  get "/welcome", to: "welcome#index", as: "welcome"
  get "/discramer", to: "discramer#index", as: "discramer"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace "api" do
    resources :works, only: %i(show) do
      resources :stages, only: %i(show) do
        resource :progress, only: %i(show update), controller: "works/stages/progresses"
      end
    end
    resources :pages, only: %i(show update)
  end

  resources :users
  resources :works
  resources :pages, only: %i(create destroy)

  resources :works, only: %i(show) do
    resources :stages, only: %i(index new create show edit update destroy), controller: "works/stages"
  end
end

app/models/work.rb
# frozen_string_literal: true

class Work < ApplicationRecord
  belongs_to :user
  has_many :progresses, dependent: :destroy
  has_many :pages, dependent: :destroy
  has_many :stages, dependent: :destroy

  validates :title, presence: true, length: { maximum: 40 }, uniqueness: { scope: :user_id }
  validate :deadline_cannnot_be_in_the_past

  def deadline_cannnot_be_in_the_past
    if deadline.present? && deadline < Date.today
      errors.add(:deadline, ": 過去の日時は設定できません")
    end
  end
end

app/controllers/api/works/stages/progresses_controller.rb
# frozen_string_literal: true

class Api::Works::Stages::ProgressesController < ApplicationController
  def show
    @progress = Progress.find_by(
      work_id: params[:work_id],
      stage_id: params[:stage_id],
      page_id: params[:page_id]
    )
  end

  def update
    progress = Progress.find_by(
      work_id: params[:work_id],
      stage_id: params[:stage_id],
      page_id: params[:page_id]
    )

    if progress.update(status: params[:status])
      render json: progress, status: :ok
    else
      render json: progress.errors, status: :unprocessable_entity
    end
  end
end

app/controllers/works/stages_controller.rb
# frozen_string_literal: true

class Works::StagesController < ApplicationController
  before_action :set_work, only: %i(index show new edit)

  def index
    @stages = @work.stages.order(:created_at)
  end

  def show
    @stage = Stage.find(params[:id])
    @progresses = @work.progresses.where(stage: @stage).order(:page_id)
  end

  def new
    @stage = Stage.new
  end

  def create
    work = Work.find(params[:work_id])
    @stage = Stage.new(stage_params)
    @stage.work = work

    if @stage.save
      work.pages.each do |page|
        Progress.create(work: work, stage: @stage, page: page)
      end
      redirect_to work_stages_path(work), notice: "#{@stage.name}が登録されました"
    else
      flash.now[:alert] = "入力項目に誤りがあります"
      render "new"
    end
  end

  def edit
    @stage = Stage.find(params[:id])
  end

  def update
    @stage = Stage.find(params[:id])

    if @stage.update(stage_params)
      redirect_to work_stages_path(@stage.work), notice: "工程を更新しました"
    else
      flash.now[:alert] = "入力項目に誤りがあります"
      render "edit"
    end
  end

  def destroy
    stage = Stage.find(params[:id])
    stage.destroy
    redirect_to work_stages_path(stage.work), notice: "工程を削除しました"
  end

  private
    def stage_params
      params.require(:stage).permit(
        :name
      )
    end

    def set_work
      @work = Work.find(params[:work_id])
    end
end

app/controllers/works_controller.rb
# frozen_string_literal: true

class WorksController < ApplicationController
  def index
    @works = current_user.works
  end

  def new
    @work = Work.new
  end

  def show
    @work = find_work
  end

  def create
    @work = Work.new(work_params)
    @work.user = current_user
    total_page = params[:work][:total_page].to_i

    if @work.save
      total_page.times do
        Page.create(work: @work)
      end
      redirect_to work_path(@work), notice: "#{@work.title}が登録されました"
    else
      flash.now[:alert] = "入力項目に誤りがあります"
      render "new"
    end
  end

  def edit
    @work = find_work
  end

  def update
    @work = find_work

    if @work.update(work_params)
      redirect_to work_path(@work), notice: "#{@work.title}の情報が変更されました"
    else
      flash.now[:alert] = "入力項目に誤りがあります"
      render "edit"
    end
  end

  def destroy
    work = find_work
    work.destroy
    redirect_to works_path, notice: "#{work.title}を削除しました"
  end

  private
    def work_params
      params.require(:work).permit(
        :title,
        :deadline
      )
    end

    def find_work
      current_user.works.find(params[:id])
    end
end

app/views/works/_work-header.html.slim
- if @work
  .work-header
    .work-header__title
      = @work.title
      .work-header__title-item
        = link_to edit_work_path(@work)
          i.fas.fa-cog
    .work-header__deadline
      | 締切まであと
      span
        = (@work.deadline - Date.today).numerator
      | 日

app/views/works/edit.html.slim
.page-body
  = render "work-header"
  .container
    .form-container
      .form-title
        | 原稿情報の編集

      .form-body
        - if @work.errors.present?
          ul.error-messages
            - @work.errors.full_messages.each do |message|
              li.error-message
                = message

        .form-items
          = form_with model: @work, local: true do |f|
            .form-item
              = f.label :title, class: "form-item__label"
              = f.text_field :title, class: "form-item__text"

            .form-item
              = f.label :deadline, class: "form-item__label"
              = f.date_field :deadline, class: "form-item__text"

            .form-item
              = f.submit nil, class: "a-button is-submit"

            .form-item
              = link_to "戻る", request.referer, class: "form-item__link"

app/views/works/index.html.slim
.page-body
  .container
    .works-table
      .works-table__head
        | 原稿一覧
      - @works.each do |work|
        .works-table__thread
          .works-table__title
            = link_to "#{work.title}", work_path(work), class: "works-table__link"
          .works-table__buttons
            = link_to "編集", edit_work_path(work), class: "works-table__button is-info"
            = link_to "削除", work, method: :delete,  data: { confirm: "#{work.title}を削除します。よろしいですか？" }, class: "works-table__button is-danger"
    .works-tools
      .works-tool
        = link_to "原稿を登録する", new_work_path, class: "a-button is-submit"

app/views/works/new.html.slim
.page-body
  .container
    .form-container
      .form-title
        | 新しい原稿の登録
      .form-body
        - if @work.errors.present?
          ul.error-messages
            - @work.errors.full_messages.each do |message|
              li.error-message
                = message

        .form-items
          = form_with model: @work, local: true do |f|
            .form-item
              = f.label :title, class: "form-item__label"
              = f.text_field :title, class: "form-item__text"

            .form-item
              = f.label :total_page, class: "form-item__label"
              .form-item__select
                = f.select :total_page, (4..40).map{ |n| n if n.even? }.compact!

            .form-item
              = f.label :deadline, class: "form-item__label"
              = f.date_field :deadline, value: Time.current.strftime("%Y-%m-%d"), class: "form-item__text"

            .form-item
              = f.submit nil, class: "a-button is-submit"

            .form-item
              = link_to "戻る", request.referer, class: "form-item__link"

app/views/works/show.html.slim
.page-body
  = render "work-header"
  .container
    .card
      .card-tabs
        = render "card/card_tabs", work: @work
      .card-list
        - if @progresses
          = render partial: "progresses/progress", collection: @progresses, as: :progress
        - else
          .card-info-items
            ul.card-info-item
              li.card-info-item__title
                i.fas.fa-bookmark.is-left-icon
                | タイトル
              li.card-info-item__body
                = @work.title
            ul.card-info-item
              li.card-info-item__title
                i.fas.fa-copy.is-left-icon
                | ページ数
              li.card-info-item__body
                = @work.pages.length
                | p
            ul.card-info-item
              li.card-info-item__title
                i.fas.fa-calendar-alt.is-left-icon
                | 締切
              li.card-info-item__body
                = @work.deadline
            ul.card-info-item
              li.card-info-item__title
                i.fas.fa-chart-bar.is-left-icon
                | 進み具合
              ul.card-info-item__body
                - @work.stages.each do |stage|
                  - completed_pages = @work.progresses.where(stage: stage, status: 2).size
                  - total_pages     = @work.pages.size
                  li.card-info-item__column
                    = stage.name
                    = number_to_percentage(completed_pages.fdiv(total_pages) * 100, precision: 0)