config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "works#index"

  get "/welcome", to: "welcome#index", as: "welcome"
  get "/discramer", to: "discramer#index", as: "discramer"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace "api" do
    resources :works, only: %i(show) do
      resources :stages, only: %i(show) do
        resource :progress, only: %i(show update), controller: "works/stages/progresses"
      end
    end
    resources :pages, only: %i(show update)
  end

  resources :users
  resources :works
  resources :pages, only: %i(create destroy)

  resources :works, only: %i(show) do
    resources :stages, only: %i(index new create show edit update destroy), controller: "works/stages"
  end
end

app/models/stage.rb
# frozen_string_literal: true

class Stage < ApplicationRecord
  belongs_to :work
  has_many :progresses, dependent: :destroy

  validates :name, presence: true, length: { maximum: 8 }, uniqueness: { scope: :work_id }
end

app/models/work.rb
# frozen_string_literal: true

class Work < ApplicationRecord
  belongs_to :user
  has_many :progresses, dependent: :destroy
  has_many :pages, dependent: :destroy
  has_many :stages, dependent: :destroy

  validates :title, presence: true, length: { maximum: 40 }, uniqueness: { scope: :user_id }
  validate :deadline_cannnot_be_in_the_past

  def deadline_cannnot_be_in_the_past
    if deadline.present? && deadline < Date.today
      errors.add(:deadline, ": 過去の日時は設定できません")
    end
  end
end

app/controllers/api/works/stages/progresses_controller.rb
# frozen_string_literal: true

class Api::Works::Stages::ProgressesController < ApplicationController
  def show
    @progress = Progress.find_by(
      work_id: params[:work_id],
      stage_id: params[:stage_id],
      page_id: params[:page_id]
    )
  end

  def update
    progress = Progress.find_by(
      work_id: params[:work_id],
      stage_id: params[:stage_id],
      page_id: params[:page_id]
    )

    if progress.update(status: params[:status])
      render json: progress, status: :ok
    else
      render json: progress.errors, status: :unprocessable_entity
    end
  end
end

app/controllers/works/stages_controller.rb
# frozen_string_literal: true

class Works::StagesController < ApplicationController
  before_action :set_work, only: %i(index show new edit)

  def index
    @stages = @work.stages.order(:created_at)
  end

  def show
    @stage = Stage.find(params[:id])
    @progresses = @work.progresses.where(stage: @stage).order(:page_id)
  end

  def new
    @stage = Stage.new
  end

  def create
    work = Work.find(params[:work_id])
    @stage = Stage.new(stage_params)
    @stage.work = work

    if @stage.save
      work.pages.each do |page|
        Progress.create(work: work, stage: @stage, page: page)
      end
      redirect_to work_stages_path(work), notice: "#{@stage.name}が登録されました"
    else
      flash.now[:alert] = "入力項目に誤りがあります"
      render "new"
    end
  end

  def edit
    @stage = Stage.find(params[:id])
  end

  def update
    @stage = Stage.find(params[:id])

    if @stage.update(stage_params)
      redirect_to work_stages_path(@stage.work), notice: "工程を更新しました"
    else
      flash.now[:alert] = "入力項目に誤りがあります"
      render "edit"
    end
  end

  def destroy
    stage = Stage.find(params[:id])
    stage.destroy
    redirect_to work_stages_path(stage.work), notice: "工程を削除しました"
  end

  private
    def stage_params
      params.require(:stage).permit(
        :name
      )
    end

    def set_work
      @work = Work.find(params[:work_id])
    end
end

app/controllers/works_controller.rb
# frozen_string_literal: true

class WorksController < ApplicationController
  def index
    @works = current_user.works
  end

  def new
    @work = Work.new
  end

  def show
    @work = find_work
  end

  def create
    @work = Work.new(work_params)
    @work.user = current_user
    total_page = params[:work][:total_page].to_i

    if @work.save
      total_page.times do
        Page.create(work: @work)
      end
      redirect_to work_path(@work), notice: "#{@work.title}が登録されました"
    else
      flash.now[:alert] = "入力項目に誤りがあります"
      render "new"
    end
  end

  def edit
    @work = find_work
  end

  def update
    @work = find_work

    if @work.update(work_params)
      redirect_to work_path(@work), notice: "#{@work.title}の情報が変更されました"
    else
      flash.now[:alert] = "入力項目に誤りがあります"
      render "edit"
    end
  end

  def destroy
    work = find_work
    work.destroy
    redirect_to works_path, notice: "#{work.title}を削除しました"
  end

  private
    def work_params
      params.require(:work).permit(
        :title,
        :deadline
      )
    end

    def find_work
      current_user.works.find(params[:id])
    end
end

app/views/works/stages/_form.html.slim
- if stage.errors.present?
  ul.error-messages
    - stage.errors.full_messages.each do |message|
      li.error-message
        = message

.form-items
  = form_with model: [:work, stage], local: true do |f|
    .form-item
      = f.label :name, class: "form-item__label"
      = f.text_field :name, class: "form-item__text", placeholder: "線画"
    
    .form-item
      = f.submit nil, class: "a-button is-submit"

    .form-item
      = link_to "戻る", request.referer, class: "form-item__link"

app/views/works/stages/edit.html.slim
.page-body
  = render "works/work-header"
  .container
    .form-container
      .form-title
        | 工程の編集

      .form-body
        = render "form", stage: @stage

app/views/works/stages/index.html.slim
.page-body
  = render "works/work-header"
  .container
    .stages-table
      .stages-table__head
        | 工程一覧
      - @stages.each do |stage|
        .stages-table__thread
          .stages-table__name
            =  stage.name
          .stages-table__buttons
            = link_to "編集", edit_work_stage_path(@work, stage), class: "stages-table__button is-info"
            = link_to "削除", work_stage_path(@work, stage), method: :delete,  data: { confirm: "#{stage.name}を削除します。よろしいですか？" }, class: "stages-table__button is-danger"

    .stages-tools
      .stages-tool
        = link_to "工程を追加", new_work_stage_path(@work), class: "a-button is-submit"
      .stages-tool
        = link_to "キャンセル", work_path(@work), class: "a-button stages-tool__button"

app/views/works/stages/new.html.slim
.page-body
  = render "works/work-header"
  .container
    .form-container
      .form-title
        | なにをやる？

      .form-body
        = render "form", stage: @stage

app/views/works/stages/show.html.slim
.page-body
  = render "works/work-header"
  .container
    .card
      .card-tabs
        = render "card/card_tabs", work: @work
      .card-list
        = render partial: "progresses/progress", collection: @progresses, as: :progress
      .card-footer
        .card-footer__items
          .card-footer__item
            i.fas.fa-plus.card-footer__item-icon
            = form_with url: pages_path, local: true do |f|
              = hidden_field_tag :work_id, @work.id
              = f.submit "ページを増やす", class: "a-button is-submit card-footer__item-icon-link"