config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "works#index"

  get "/welcome", to: "welcome#index", as: "welcome"
  get "/discramer", to: "discramer#index", as: "discramer"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace "api" do
    resources :works, only: %i(show) do
      resources :stages, only: %i(show) do
        resource :progress, only: %i(show update), controller: "works/stages/progresses"
      end
    end
    resources :pages, only: %i(show update)
  end

  resources :users
  resources :works
  resources :pages, only: %i(create destroy)

  resources :works, only: %i(show) do
    resources :stages, only: %i(index new create show edit update destroy), controller: "works/stages"
  end
end

app/views/card/_card_tabs.html.slim
.card-tabs
  .container
    ul.card-tabs__items
      li.card-tabs__item
        = link_to "基本情報", work_path(work), class: "card-tabs__item-link"
      - work.stages.each do |stage|
        - if Progress.exists?(work_id: work, stage_id: stage)
          li.card-tabs__item
              = link_to work_stage_path(work_id: work, id: stage), class: "card-tabs__item-link #{current_card_tab_or_not("#{stage.id}")}"
                = stage.name
      - if work.stages.exists?
        li.card-tabs__item
          i.fas.fa-wrench.card-tabs__icon
          = link_to "工程を編集", work_stages_path(work_id: work), class: "card-tabs__item-link"
      - else
        li.card-tabs__item
          i.fas.fa-plus-circle.card-tabs__icon
          = link_to "工程を追加", new_work_stage_path(work_id: work), class: "card-tabs__item-link"