config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "works#index"

  get "/welcome", to: "welcome#index", as: "welcome"
  get "/discramer", to: "discramer#index", as: "discramer"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace "api" do
    resources :works, only: %i(show) do
      resources :stages, only: %i(show) do
        resource :progress, only: %i(show update), controller: "works/stages/progresses"
      end
    end
    resources :pages, only: %i(show update)
  end

  resources :users
  resources :works
  resources :pages, only: %i(create destroy)

  resources :works, only: %i(show) do
    resources :stages, only: %i(index new create show edit update destroy), controller: "works/stages"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private
    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def login_required
      unless current_user
        redirect_to welcome_path, alert: "ログインしてください"
      end
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_favicons.html.erb
<%= favicon_link_tag("/favicon.ico") %>
<link rel="apple-touch-icon", sizes="180x180" href="/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
<link rel="mask-icon" href="/favicons/favicon.svg">

app/views/application/_flash.html.slim
- if notice
  .flash.is-notice
    .container
      .flash__container
        p.flash__message
          = notice
- if alert
  .flash.is-alert
    .container
      .flash__container
        p.flash__message
          = alert

app/views/application/_footer.html.slim
footer.footer
  .footer__inner
    .footer__items
      .footer__item
        = link_to "免責事項", discramer_path
      .footer__item
        = link_to "GitHub", "https://github.com/UsaMomokawa/gen"
    .footer__copyright
      i.far.fa-copyright
      = link_to "UsaMomokawa" , "https://github.com/UsaMomokawa/gen", class: "footer__copyright-link"
      = "2019"

app/views/application/_header.html.slim
header.header
  .header__container
    .header-title
      = link_to "GEN", welcome_path
    .header_links
      .header-links__item
        label.header-links__link.test-show-menu(for="header-menu")
          i.fas.fa-bars.header-links__link-icon
        input.a-toggle-checkbox#header-menu(type="checkbox")
        .header-dropdown
          label.header-dropdown__background(for="header-menu")
          .header-dropdown__inner
            - if current_user
              ul.header-dropdown__items
                li.header-dropdown__item
                  = link_to "原稿一覧", works_path, class: "header-dropdown__item-link"
                li.header-dropdown__item
                  = link_to "アカウント編集", edit_user_path(current_user), class: "header-dropdown__item-link"
                li.header-dropdown__item
                  = link_to "ログアウト", logout_path, method: :delete, notice: "ログアウトしました", class: "header-dropdown__item-link"
            - else
              ul.header-dropdown__items
                li.header-dropdown__item
                  = link_to "アカウント登録", new_user_path, class: "header-dropdown__item-link"
                li.header-dropdown__item
                  = link_to "ログイン", login_path, class: "header-dropdown__item-link"
                        